[project]
name = "fileexplorer"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]",
    "uvicorn>=0.40.0",
    "jinja2",
    "pytest"
]
